# Profile information
[profile]
name = "Phearak S. Tha"
bio = "Software Engineer • Photographer"

# Social media handle
[social]
twitter = "thasophearak"
github = "thasophearak"
instagram = ""
youtube = "thasophearak"
facebook = ""

[moul]
build = "local" # remote

[deployment]
target = "cloudflare-pages" # vercel | netlify | fly.io | railway
