# Profile information
[profile]
name = "Phearak S. Tha"
bio = "Software Engineer • Photographer"

# Social media handle
[social]
twitter = "thasophearak"
github = "thasophearak"
instagram = "thasophearak"
youtube = ""
facebook = ""