name = "moul-app"
main = "build/index.js"

account_id = "6959eb2609146d198c9eb29a1587a881"
# route = ""
compatibility_date = "2022-05-19"
workers_dev = true

kv_namespaces = [
  { binding = "MOUL_KV", id = "b8e217b1ca554156a876ce6ea35e14f5" }
]

[site]
bucket = "./public"
 
[build]
command = "npm run build"
