[deployment]
target = "cloudflare-pages" # Other possible value are "vercel" | "netlify"

[profile]
  bio = ""
  name = ""

[social]
  facebook = ""
  github = ""
  instagram = ""
  twitter = ""
  youtube = ""
